name: CI pipeline using called workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'examples/**'

  workflow_dispatch:
    inputs:
      language:
        description: 'Programming Language'
        required: true
        default: 'java'
      version:
        description: 'Java Version'
        required: true
        default: '17'
      distribution:
        description: 'Java Distribution'
        required: true
        default: 'adopt'
jobs:
  code_analyze:
    uses: kishore3github/github-actions/.github/workflows/code_scanning.yaml@main
    with:
      language: ${{ github.event.inputs.language }}
      version: ${{ github.event.inputs.version }}
      distribution: ${{ github.event.inputs.distribution }}
      # language: 'java'
      # version: '17'
      # distribution: 'adopt'
      
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build_and_push_image_to_dockerhub:
    needs: code_analyze
    uses: kishore3github/github-actions/.github/workflows/java-ci.yaml@main
    with:
      repoName: ${{ github.repository }}
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
